const isLiveMode = process.env.NEXT_PUBLIC_DODO_ENVIRONMENT === "live_mode";

export const PRODUCT_IDS = isLiveMode
    ? {
          starterMonthly: "pdt_0NZGBR6GtydxMB2lNeh09",
          starterAnnual: "pdt_0NZGBRV0VGyAffgoPOiMx",
          proMonthly: "pdt_0NZGBRrun07eXzoWlmzm2",
          proAnnual: "pdt_0NZGBSH8bWPajakeSOO8B",
          agencyMonthly: "pdt_0NZGBScekA4L6yNm7r3BX",
          agencyAnnual: "pdt_0NZGBSvywqWyfQBbnGecS",
      }
    : {
          starterMonthly: "pdt_0NY6k5d7b4MxSsVM7KzEV",
          starterAnnual: "pdt_0NY6kJuPXxJUv7SFNbQOB",
          proMonthly: "pdt_0NY6llF7a0oFiFsaeVOW7",
          proAnnual: "pdt_0NY6lyuXXpnq6BWWOeDTy",
          agencyMonthly: "pdt_0NZFx5ffGwT1YxA1hGbe4",
          agencyAnnual: "pdt_0NZFxhZt01qOI9OLNEaSd",
      };

export interface Plan {
    name: string;
    description: string;
    monthly: number;
    annually: number;
    originalMonthly?: number;
    originalAnnually?: number;
    features: string[];
    featured: boolean;
    badge?: string;
    dodoProductIdMonthly: string;
    dodoProductIdYearly: string;
}

export const plans: Record<string, Plan> = {
    pro: {
        name: "Pro",
        badge: "Most Popular",
        description: "Full power for serious creators",
        monthly: 18,
        annually: 12.5,
        originalMonthly: 29,
        originalAnnually: 29,
        features: [
            "400 Minutes/Month",
            "Without Watermark",
            "Up to 3h File Length",
            "4K Clip Quality",
            "5 Social Accounts",
            "3 Workspaces",
            "3 Team Members",
            "Highest Queue Priority",
            "──── AI Features ────",
            "AI Viral Clip Detection",
            "AI Reframe (Auto-Zoom)",
            "AI Hook Overlay",
            "Viral Score Analysis",
            "──── Backgrounds ────",
            "Split Screen (Subway Surfer, Minecraft...)",
            "Blur, Mirror, Zoom Backgrounds",
            "Gradient Backgrounds",
            "──── Captions ────",
            "AI Captions (Word-by-Word)",
            "Caption Animations",
            "Custom Caption Styles",
            // "──── Translation ────",
            // "Translate to 28+ Languages",
            // "AI Voice Dubbing",
            "──── Export ────",
            "Batch Export",
            "Social Media Scheduling",
            "Brand Kit",
            "Founder Personal Support",
        ],
        featured: true,
        dodoProductIdMonthly: PRODUCT_IDS.proMonthly,
        dodoProductIdYearly: PRODUCT_IDS.proAnnual,
    },
    agency: {
        name: "Agency",
        badge: "Best Value",
        description: "For agencies and teams that need it all",
        monthly: 99,
        annually: 49,
        originalMonthly: 149,
        originalAnnually: 99,
        features: [
            "5,000 Minutes/Month",
            "Without Watermark",
            "Up to 3h File Length",
            "4K Clip Quality",
            "Unlimited Social Accounts",
            "10 Workspaces",
            "10 Team Members",
            "Highest Queue Priority",
            "──── AI Features ────",
            "AI Viral Clip Detection",
            "AI Reframe (Auto-Zoom)",
            "AI Hook Overlay",
            "Viral Score Analysis",
            "──── Backgrounds ────",
            "Split Screen (Subway Surfer, Minecraft...)",
            "Blur, Mirror, Zoom Backgrounds",
            "Gradient Backgrounds",
            "──── Captions ────",
            "AI Captions (Word-by-Word)",
            "Caption Animations",
            "Custom Caption Styles",
            // "──── Translation ────",
            // "Translate to 28+ Languages",
            // "AI Voice Dubbing",
            "──── Export ────",
            "Batch Export",
            "Social Media Scheduling",
            "Brand Kit",
            "──── Agency Perks ────",
            "Team Collaboration",
            "Priority Support",
            "Founder Personal Support",
        ],
        featured: false,
        dodoProductIdMonthly: PRODUCT_IDS.agencyMonthly,
        dodoProductIdYearly: PRODUCT_IDS.agencyAnnual,
    },
    starter: {
        name: "Starter",
        description: "Everything you need to get started",
        monthly: 12,
        annually: 10,
        originalMonthly: 19,
        originalAnnually: 19,
        features: [
            "200 Minutes/Month",
            "Without Watermark",
            "Up to 2h File Length",
            "1080p Clip Quality",
            "1 Social Account",
            "1 Workspace",
            "1 Team Member",
            "High Queue Priority",
            "──── AI Features ────",
            "AI Viral Clip Detection",
            "AI Reframe (Auto-Zoom)",
            "AI Hook Overlay",
            "Viral Score Analysis",
            "──── Backgrounds ────",
            "Split Screen (Subway Surfer, Minecraft...)",
            "Blur, Mirror, Zoom Backgrounds",
            "Gradient Backgrounds",
            "──── Captions ────",
            "AI Captions (Word-by-Word)",
            "Caption Animations",
            "Custom Caption Styles",
            // "──── Translation ────",
            // "Translate to 28+ Languages",
            // "AI Voice Dubbing",
            "──── Export ────",
            "Batch Export",
            "Social Media Scheduling",
            "Brand Kit",
        ],
        featured: false,
        dodoProductIdMonthly: PRODUCT_IDS.starterMonthly,
        dodoProductIdYearly: PRODUCT_IDS.starterAnnual,
    },
};
